In [ ]:
# 1. Understanding BERT and XLM-RoBERTa

In [ ]:
# Importing the tokenizer classes for BERT and XLM-RoBERTa from the Hugging Face Transformers library
from transformers import BertTokenizer, XLMRobertaTokenizer

In [ ]:
# Loading the pre-trained BERT tokenizer from the 'bert-base-uncased' model
# This is initializing a tokenizer trained on lowercase English text
bert_tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

In [ ]:
# Loading the pre-trained XLM-RoBERTa tokenizer from the 'xlm-roberta-base' model
# This is initializing a tokenizer trained on multilingual data (100+ languages)
xlmr_tokenizer = XLMRobertaTokenizer.from_pretrained("xlm-roberta-base")

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/615 [00:00<?, ?B/s]

In [5]:
# 2. Tokenizing Text

# Defining a sample sentence to tokenize
sample_text = "It's truly inspiring how the bootcamp uploads class content without ever reading it — a bold commitment to surprise-based learning."

In [6]:
# Tokenizing the sample text using BERT tokenizer

# Using encode_plus to get input_ids and attention_mask
bert_tokens = bert_tokenizer.encode_plus(
    sample_text,                       # Supplying the sentence to be tokenized
    add_special_tokens=True,          # Adding [CLS] and [SEP] automatically
    max_length=32,                    # Limiting/padding the sentence to 32 tokens
    padding='max_length',             # Padding with zeros if sentence is shorter than 32 tokens
    truncation=True,                  # Truncating if the sentence is longer than 32 tokens
    return_attention_mask=True,       # Including the attention mask to indicate real vs padded tokens
    return_tensors='pt'               # Returning as PyTorch tensors (we can use 'tf' for TensorFlow)
)

# encode_plus to get:
# input_ids: The numeric ID of each token, including special tokens like [CLS] and [SEP]
# attention_mask:	A binary mask (1 = real token, 0 = padding token), so the model knows what to ignore

In [7]:
# Printing the BERT input IDs
print("BERT input_ids:", bert_tokens['input_ids'])

# Printing the BERT attention mask
print("BERT attention_mask:", bert_tokens['attention_mask'])

# Decoding input IDs back into readable tokens
print("Decoded tokens:", bert_tokenizer.decode(bert_tokens['input_ids'][0]))

BERT input_ids: tensor([[  101,  2009,  1005,  1055,  5621, 18988,  2129,  1996,  9573, 26468,
          2039, 11066,  2015,  2465,  4180,  2302,  2412,  3752,  2009,  1517,
          1037,  7782,  8426,  2000,  4474,  1011,  2241,  4083,  1012,   102,
             0,     0]])
BERT attention_mask: tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 0, 0]])
Decoded tokens: [CLS] it's truly inspiring how the bootcamp uploads class content without ever reading it — a bold commitment to surprise - based learning. [SEP] [PAD] [PAD]

In [8]:
# Tokenizing the same sentence using XLM-RoBERTa tokenizer
xlmr_tokens = xlmr_tokenizer.encode_plus(
    sample_text,
    add_special_tokens=True,          # Adding <s> and </s> automatically
    max_length=32,
    padding='max_length',
    truncation=True,
    return_attention_mask=True,
    return_tensors='pt'
)

In [9]:
# Printing the XLM-RoBERTa input IDs
print("XLM-RoBERTa input_ids:", xlmr_tokens['input_ids'])

# Printing the XLM-RoBERTa attention mask
print("XLM-RoBERTa attention_mask:", xlmr_tokens['attention_mask'])

# Decoding the tokens back to human-readable form
print("Decoded tokens:", xlmr_tokenizer.decode(xlmr_tokens['input_ids'][0]))

XLM-RoBERTa input_ids: tensor([[     0,   1650,     25,      7,  87607,  16877,    214,   3642,     70,
          49935,  27034,  70622,      7,  18507,  10941,  15490,  17669,  16454,
            442,    292,     10,      6,  65665, 166794,     47,  55640,      9,
          77007,  52080,      5,      2,      1]])
XLM-RoBERTa attention_mask: tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 0]])
Decoded tokens: <s> It's truly inspiring how the bootcamp uploads class content without ever reading it — a bold commitment to surprise-based learning.</s><pad>

# Tokenizing Text (notes for me):

- input_ids:	The numerical form of the text for the model
- attention_mask:	A mask that tells the model what to focus on (1 = real word, 0 = padding)
- decode():	Converts token IDs back to text for us to read
- add_special_tokens:	Adds [CLS], [SEP] (BERT) or <s>, </s> (XLM-RoBERTa) automatically
- padding='max_length':	Pads to the length we set (here: 32)
- truncation=True:	Cuts off text if it’s too long
- return_attention_mask:	Tells model which tokens are padding
- return_tensors='pt':	Returns PyTorch-ready format
- So the code we write doesn't really change — but the tokenizer's internal logic and output does, based on which model you're using.

In [ ]:
# 3. Preparing Input Data for the Model

In [10]:
# Defining the text again
sample_text = "Wow, it's so impressive how the bootcamp uploads content they clearly haven't read!"

In [14]:
# Preparing input for BERT tokenizer

# Tokenizing and formatting the input for BERT
bert_tokens = bert_tokenizer.encode_plus(
    sample_text,                        # Passing the sentence to be tokenized
    add_special_tokens=True,           # Adding [CLS] at the beginning and [SEP] at the end
    max_length=32,                     # Setting the max length of the sequence
    padding='max_length',              # Padding with zeros if sentence is shorter than 32 tokens
    truncation=True,                   # Truncating tokens beyond the max length
    return_attention_mask=True,        # Returning the attention mask (1s and 0s)
    return_tensors='pt'                # Returning PyTorch tensors for model input
)

In [15]:
#  Printing and inspecting BERT input

# Printing input_ids for BERT (these are token numbers the model understands)
print("BERT input_ids:", bert_tokens['input_ids'])

# Printing attention_mask for BERT (1 = real token, 0 = padding)
print("BERT attention_mask:", bert_tokens['attention_mask'])

# Decoding input_ids to see which tokens were used (human-readable form)
print("BERT decoded text:", bert_tokenizer.decode(bert_tokens['input_ids'][0]))

BERT input_ids: tensor([[  101, 10166,  1010,  2009,  1005,  1055,  2061,  8052,  2129,  1996,
          9573, 26468,  2039, 11066,  2015,  4180,  2027,  4415,  4033,  1005,
          1056,  3191,   999,   102,     0,     0,     0,     0,     0,     0,
             0,     0]])
BERT attention_mask: tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         0, 0, 0, 0, 0, 0, 0, 0]])
BERT decoded text: [CLS] wow, it's so impressive how the bootcamp uploads content they clearly haven't read! [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]

In [16]:
# Checking tokenizer vocabulary and special tokens

# Printing the total number of tokens in BERT's vocabulary
print("BERT vocab size:", bert_tokenizer.vocab_size)

# Printing the special tokens used by BERT
print("BERT special tokens:", bert_tokenizer.special_tokens_map)

BERT vocab size: 30522
BERT special tokens: {'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}

[UNK] [SEP] [CLS].... These are the special tokens BERT uses internally.

In [18]:
# preparing input for XLM-RoBERTa tokenizer (same logic)

# Tokenizing and formatting the input for XLM-RoBERTa
xlmr_tokens = xlmr_tokenizer.encode_plus(
    sample_text,
    add_special_tokens=True,           # Adding <s> at the beginning and </s> at the end
    max_length=32,
    padding='max_length',
    truncation=True,
    return_attention_mask=True,
    return_tensors='pt'
)

In [19]:
# Printing and inspecting XLM-RoBERTa input

print("XLM-RoBERTa input_ids:", xlmr_tokens['input_ids'])
print("XLM-RoBERTa attention_mask:", xlmr_tokens['attention_mask'])
print("XLM-RoBERTa decoded text:", xlmr_tokenizer.decode(xlmr_tokens['input_ids'][0]))

XLM-RoBERTa input_ids: tensor([[     0,  53505,      4,    442,     25,      7,    221, 218898,   3642,
             70,  49935,  27034,  70622,      7,  10941,   1836, 123019,  38246,
             25,     18,  12301,     38,      2,      1,      1,      1,      1,
              1,      1,      1,      1,      1]])
XLM-RoBERTa attention_mask: tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
         0, 0, 0, 0, 0, 0, 0, 0]])
XLM-RoBERTa decoded text: <s> Wow, it's so impressive how the bootcamp uploads content they clearly haven't read!</s><pad><pad><pad><pad><pad><pad><pad><pad><pad>

In [20]:
# Checking XLM-RoBERTa tokenizer info

print("XLM-RoBERTa vocab size:", xlmr_tokenizer.vocab_size)
print("XLM-RoBERTa special tokens:", xlmr_tokenizer.special_tokens_map)

XLM-RoBERTa vocab size: 250002
XLM-RoBERTa special tokens: {'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>', 'sep_token': '</s>', 'pad_token': '<pad>', 'cls_token': '<s>', 'mask_token': '<mask>'}

# Preparing input data (For me):
- Padding:	Making short inputs equal length
- Truncation:	Cutting off extra-long inputs
- Special Tokens:	Marking start/end of sentence
- Attention Mask:	Letting the model ignore padding
- Tensors:	Formatting inputs for PyTorch

# The code looks the same in both tokenization (2) and preparing input data (3)because we’re using the same function tokenizer.encode_plus() in both
But the difference is in how many options/parameters we activate inside that function.

In [26]:
# 4. Loading and Exploring the Dataset

from google.colab import files
uploaded = files.upload()

Saving train.csv to train.csv

In [28]:
# Importing pandas for data handling (Loading the dataset using pandas)
import pandas as pd

# Reading the uploaded CSV file into a DataFrame
df = pd.read_csv("train.csv")

In [29]:
df.head()

,id,premise,hypothesis,lang_abv,language,label
0,5130fd2cb5,and these comments were considered in formulat...,The rules developed in the interim were put to...,en,English,0
1,5b72532a0b,These are issues that we wrestle with in pract...,Practice groups are not permitted to work on t...,en,English,2
2,3931fbe82a,Des petites choses comme celles-là font une di...,J'essayais d'accomplir quelque chose.,fr,French,0
3,5622f0c60b,you know they can't really defend themselves l...,They can't defend themselves because of their ...,en,English,0
4,86aaa48b45,ในการเล่นบทบาทสมมุติก็เช่นกัน โอกาสที่จะได้แสด...,เด็กสามารถเห็นได้ว่าชาติพันธุ์แตกต่างกันอย่างไร,th,Thai,1

In [30]:
df.shape
# To understand how many samples (rows) and how many columns (features/labels) the dataset contains

(12120, 6)

In [31]:
print("Columns:", df.columns.tolist())

Columns: ['id', 'premise', 'hypothesis', 'lang_abv', 'language', 'label']

In [ ]:
# 5. Creating Cross-Validation Folds

# Here We’re going to split our dataset into multiple training/validation subsets, so we can:
# - Evaluate our model more reliably
# - Avoid overfitting
# - Make better use of the available data
# We’ll use Stratified K-Fold, which ensures each fold has a balanced distribution of labels (important for classification problems like ours with 3 classes: 0, 1, 2).

In [32]:
# Importing StratifiedKFold from scikit-learn
from sklearn.model_selection import StratifiedKFold

# (Bringing in the K-Fold splitter that makes sure each fold keeps similar label proportions, which helps our evaluation be more fair and realistic)

In [34]:
# Creating a new column in the DataFrame to hold the fold index
df['kfold'] = -1

# This will store the fold number each row belongs to (0 to 4 if we use 5 folds)

In [35]:
# Shuffling the dataset before splitting
df = df.sample(frac=1).reset_index(drop=True)

# here we:
#  Shuffle the rows randomly (good practice before splitting into folds)
# Resetting the index so the row order looks clean after shuffling

In [36]:
# Defining the Stratified K-Fold object (5 folds)
kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# here we are:
# Telling scikit-learn "Split this data into 5 folds, and keep label distribution balanced."
# Setting random_state=42 for reproducibility (same split every time)

In [37]:
# Creating the folds by assigning fold numbers
for fold, (train_idx, val_idx) in enumerate(kf.split(X=df, y=df['label'])):
    # Assigning the fold number to the validation set in that fold
    df.loc[val_idx, 'kfold'] = fold

# here we are:
# Looping through each fold split
# Assigning the validation rows for that fold a value in the kfold column
# After this, every row will have a number in kfold column from 0 to 4

In [38]:
# Previewing the new dataset structure with fold assignments
df.head()

,id,premise,hypothesis,lang_abv,language,label,kfold
0,d76beeb9b0,"Затем идет Бона - центр плетения корзин, кото...",Бона известна танцами кечак.,ru,Russian,1,2
1,3b9aba877c,"Die Vorstellung, dass zwei Studierende in ihre...",Es ist schwierig für College-Studente im erste...,de,German,1,0
2,53c744b6a5,"这个体育馆，和在这里举行的活动叫agon,一个原来意味着竞争的希腊词",“agon“这个词最初在希腊语中意为竞争。,zh,Chinese,0,3
3,7db3de7555,Auf den Saronic Inseln dauert die Saison länge...,Die Saronischen Inseln haben ausgeprägte Jahre...,de,German,0,4
4,45f242f9bd,", μικρότερες τάξεις, χρήση της τεχνολογίας) κα...",Υπάρχουν μόνο δύο ντουλάπια σε ολόκληρο το κτί...,el,Greek,1,4

In [39]:
# Checking how many samples are in each fold
print(df['kfold'].value_counts())

kfold
2    2424
0    2424
3    2424
4    2424
1    2424
Name: count, dtype: int64

summary of 5 (for me)
- we Created kfold column	To store which fold each row belongs to
- Shuffled the dataset	To ensure random mixing before splitting
- Used StratifiedKFold	To balance label distribution in each fold
- Assigned fold numbers	So we can later pick training/validation splits easily

In [41]:
#  Storing Folds in Lists (ING-style)

# Creating empty lists to store training and validation indexes
train_idx_list = []
val_idx_list = []

# Looping through folds again and storing index lists
for fold, (train_idx, val_idx) in enumerate(kf.split(X=df, y=df['label'])):
    train_idx_list.append(train_idx)
    val_idx_list.append(val_idx)